[tool.ruff]
required-version = ">=0.5.0"
line-length = 120
target-version = "py311"
exclude = ["generated"]

[tool.ruff.lint]
select = [
	"E",    # pycodestyle
	"F",    # pyflakes/autoflake
	"FURB", # refurb
	"I",    # isort
	"PERF", # performance
	"PL",   # pylint
	"SIM",  # flake8-simplify
	"RET",  # flake8-ret
	"UP",   # pyupgrade
]

ignore = [
	"E501",     # line too long
	"PLC0415",  # `import` should be at the top-level of a file
	"PLR0911",  # Too many return statements
	"PLR0912",  # Too many branches
	"PLR0913",  # Too many arguments
	"PLR0915",  # Too many statements
	"PLW1641",  # Object does not implement `__hash__`
	"PLR2004",  # Magic value used in comparison
	"PLW2901",  # Outer variable overwritten by inner target
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
